/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary': '#f3f4f6',
        'inverse-primary': '#eff6ff',
        'surface-bright': '#ffffff',
        'error': '#ef4444',
        'surface-container': '#f9fafb',
        'outline-variant': '#e5e7eb',
        'surface-container-low': '#ffffff',
        'primary': '#2563eb',
        'surface': '#ffffff',
        'primary-fixed': '#1d4ed8',
        'surface-variant': '#f3f4f6',
        'error-container': '#fee2e2',
        'surface-container-highest': '#e5e7eb',
        'surface-container-high': '#f3f4f6',
        'on-surface-variant': '#6b7280',
        'on-background': '#111827',
        'background': '#f4f5f7',
        'surface-dim': '#ffffff',
        'secondary': '#6b7280',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#f3f4f6',
        'outline': '#d1d5db',
        'surface-tint': '#eff6ff',
        'primary-fixed-dim': '#3b82f6',
        'primary-container': '#dbeafe',
        'on-primary-container': '#1e3a8a',
        'on-surface': '#1f2937',
        'on-primary': '#ffffff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Public Sans', 'sans-serif'],
        label: ['Literata', 'serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      animation: {
        'ticker': 'ticker 40s linear infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        ticker: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
